language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
before_install:
- sudo add-apt-repository ppa:duggan/bats --yes
- sudo apt-get update -qq
- sudo apt-get install -qq bats python-pip python-setuptools
- sudo pip install awscli
- aws s3 rm s3://it-jobb-i-kalmar --recursive --region eu-central-1
install:
- npm i -g gatsby
- npm install
script:
- npm run build --dd
deploy:
  provider: s3
  access_key_id: AKIAJRNJAWH5WTT2BZFA
  secret_access_key:
    secure: UOWBKcNpV2k5nV5+elBvT+VHKMXhpoHgq71Yk6BdT4CzrxhMyEeCzkfOHJdcTWfKhk3eY/+3RtqlQo9SyQvTAXW4XPZxkZ47lfUVXrw9UHJSltOSjJHFHmQu037r8WFcYjzQ9tIorpAn0tcUpLlupm70CJkY62zxJLBRoexUrGJS4D+dJ9AxEKQVl4jwS42L5RfaE1cPYypVE7c/PzmonagMDR2T1YNMJSw+CgRsmK7+L2Xm9/uPYUpWCMah53ezPp2KqiwUnf8L0LhdW94G584wqMGUumxEuJXuA2gi+Rk5z78JJmc1p3UQ5yfgk+tZpRJwVcgymAbGr7sPJrojDg65k+/r36xmelTbw9BMzroLwwgE6uvl1qQdVcOtSxXVUnGS1QBCG6O+RgI4cl2Vq0uS7aQxeg7UX/etyoUFbuYSMaTi427jtnU5E7NDfaY8kaGG4uuiMru8i9uP31ncsSz8ZzpgbieFnUj+/6z0pVpfjRkk4gqQsBP38lTWdf7RWqjD9Qab2KHjKN3tnJ8kmKXBiREH+30wKaJv4L8UIWNk4Ijpompw4IO5dz/GDftvu+8nQcq4P0GZAX687vn+mXUxIVrfNG/UnHuNdrG0Mk9/o2vdHBVqf9C7LUNph7CuZIFoczWYqCk20hp5DsMFTfqhx5QJ37+UCStRGeeeXsY=
  bucket: it-jobb-i-kalmar
  local-dir: public
  acl: public_read
  region: eu-west-1
  skip_cleanup: true
  on:
    repo: IT-jobb-Kalmar/gatsby-it-jobb-i-kalmar
after_deploy:
- aws configure set preview.cloudfront true
- aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID
  --paths "/*"
branches:
  only:
  - master
