language: node_js
node_js:
- node

cache:
  directories:
  - node_modules

before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats python-pip python-setuptools
  - sudo pip install awscli
  - echo "---- Clearing bucket it-jobb-i-kalmar"
  - aws s3 rm s3://it-jobb-i-kalmar --recursive --region eu-central-1

install:
- npm i -g gatsby
- npm install --dd

script:
- npm run build --dd

deploy:
  provider: s3
  access_key_id: AKIAJRNJAWH5WTT2BZFA
  secret_access_key:
    secure: mQgDD8Q1mT1gHeocv15jCS2+yU0ft6i/FyLThVPUO4uAci6QRYfwlcjYuhmBcsqhbtDIk5k602t3fZ3MyPt9QKtoCQI5pv1+MDHHWbuji82OvmpfwDOmlC3Dwbz5iJwddOQtFD2bsa0ea+DZZJ/DoXrxZaddSroDruP+LwlKRK/wckgYadVWstO94DSDRYeJ8wgN0NhSgW+kyAgJYA4i+U3+xX8c5K6hUMsgMqv92qGHDYeo9sRwr2oI8GQnuV8O5vEgQkMDjxEadQuC5CQeW8/avKZBkvefmI7O+9DuOf88GiyEP8bg9LE3TouTF3eePeo92aC9EgE9XnezYzxzTz+7MrzHa25blwLfq+vJD0KTTzFAf2uiC9ApYC1kKTsjbnXusipfxDPNOpxuh+266ATlUKU56uYawIKqB/M8M68eOzhE6S1v4X+bRFgvHeJaXq5ZNgtkDa/CN+OIQD+v0nBWB1D5O2H9H2Vc6I46rvOC0t3zYO/OEXPh0qMWRB7Sy9xRNOz2eYiyiA94GnIAIJoA4h4iLi2dpjrT/ijAGjuSJQMCFQpcvpm3LLDZLlXAvhMwnbbT+NZVParY2nEosvTzKiPO5taTJACCUbpEWLG9iAmfyM2eohDrMCyWUNkMVjEiiO5ygnQNp9E6neieJgVaBz4lMQ35i9/OiQUkoy4=
  # bucket: "itjobbikalmar.se"
  bucket: "it-jobb-i-kalmar"
  local-dir: public
  acl: public_read
  region: eu-west-1
  skip_cleanup: true
  on:
    repo: IT-jobb-Kalmar/gatsby-it-jobb-i-kalmar

after_deploy:
  # Allow `awscli` to make requests to CloudFront.
  - aws configure set preview.cloudfront true
  # Invalidate every object in the targeted distribution.
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"

branches:
  only:
  - master




